# Generated by Django 5.2 on 2025-05-10 05:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=100)),
                ('model_id', models.CharField(max_length=255)),
                ('dimension', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VectorStoreProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VectorStoreInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('collection_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('created', 'Created'), ('indexing', 'Indexing'), ('ready', 'Ready'), ('failed', 'Failed')], default='created', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documents', models.ManyToManyField(related_name='vector_stores', to='document.document')),
                ('embedding_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vector_stores', to='vectorstore.embeddingmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vector_stores', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='vectorstore.vectorstoreprovider')),
            ],
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='document.documentchunk')),
                ('vector_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='vectorstore.vectorstoreinstance')),
            ],
            options={
                'unique_together': {('document_chunk', 'vector_store')},
            },
        ),
    ]
